/****** Object:  Table [dbo].[Promocao]    Script Date: 02/07/2018 07:59:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Promocao](
	[ID_PROMO] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[TIPO_PROMO] [numeric](2, 0) NULL,
	[QTD_LEVE_PROMO] [numeric](10, 0) NULL,
	[QTD_PAGUE_PROMO] [numeric](10, 0) NULL,
	[VLR_PAGUE] [numeric](10, 2) NULL,
	[DESC_PROMO] [varchar](150) NULL,
 CONSTRAINT [PK__Promocao__79F0C0FAC6C67D27] PRIMARY KEY CLUSTERED 
(
	[ID_PROMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO






/****** Object:  Table [dbo].[Produto]    Script Date: 02/07/2018 07:57:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Produto](
	[ID_PRODUTO] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[ID_PROMO] [numeric](10, 0) NULL,
	[NOME] [varchar](150) NULL,
	[PRECO] [numeric](10, 2) NULL,
 CONSTRAINT [PK__Produto__69B28A520E9E2213] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Produto]  WITH CHECK ADD  CONSTRAINT [FK__Produto__ID_PROM__1273C1CD] FOREIGN KEY([ID_PROMO])
REFERENCES [dbo].[Promocao] ([ID_PROMO])
GO

ALTER TABLE [dbo].[Produto] CHECK CONSTRAINT [FK__Produto__ID_PROM__1273C1CD]
GO