//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public long ID_PRODUTO { get; set; }
        public Nullable<long> ID_PROMO { get; set; }
        public string NOME { get; set; }
        public Nullable<decimal> PRECO { get; set; }
    
        public virtual Promocao Promocao { get; set; }
    }
}
